# Generated by Django 4.0.3 on 2022-05-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='app',
            field=models.CharField(default='Django Only App', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='app',
            field=models.CharField(default='Django Only App', max_length=255),
        ),
    ]
